/*************************************************************************************
 *                                                                                   *
 * Copyright: (c) 2020 Broadcom.                                                     *
 * Broadcom Proprietary and Confidential. All rights reserved.                       *
 */

/*************************************************************************************
 *************************************************************************************
 *                                                                                   *
 *  Revision      :  Id                                                              *
 *                                                                                   *
 *  Description   :  Defines and externed arrays used for register dump              *
 */


/* THIS FILE IS GENERATED USING AN AUTOMATED SCRIPT. PLEASE DO NOT EDIT THIS FILE DIRECTLY! */

#ifndef OSPREY7_V2L8P1_API_REG_DUMP_H
#define OSPREY7_V2L8P1_API_REG_DUMP_H

#include "osprey7_v2l8p1_usr_includes.h"

/*! @file
 *  @brief Register addresses and types used for register dump APIs
 */

/*! @addtogroup APITag
 * @{
 */

/*! @defgroup SerdesAPIRegDumpTag Support for Register Dump APIs  */

/*! @addtogroup SerdesAPIRegDumpTag
 * @{
 */


/*! @def OSPREY7_V2L8P1_REG_DUMP_SECTIONS
 * The number of contiguous register address ranges that will have their contents dumped.
 */
#define OSPREY7_V2L8P1_REG_DUMP_SECTIONS  (19)

/*! @def OSPREY7_V2L8P1_REG_PLL_START
 * The register address of the first PLL register.
 * A value of 0xffff indicates there are no PLL registers for this IP.
 */
#define OSPREY7_V2L8P1_REG_PLL_START      (0xd110)

/*! @def OSPREY7_V2L8P1_REG_UC_START
 * The register address of the first UC register.
 * A value of 0xffff indicates there are no UC registers for this IP.
 */
#define OSPREY7_V2L8P1_REG_UC_START       (0xd240)
extern const uint16_t osprey7_v2l8p1_reg_dump_arr[OSPREY7_V2L8P1_REG_DUMP_SECTIONS][2];

/*! @} SerdesAPIRegDumpTag */
/*! @} APITag */

#endif /* SERDES_API_REG_DUMP_H */

