/***********************************************************************************
 *                                                                                 *
 * Copyright: (c) 2020 Broadcom.                                                   *
 * Broadcom Proprietary and Confidential. All rights reserved.                     *
 */

/***********************************************************************************
 ***********************************************************************************
 *                                                                                 *
 *  Revision      :   *
 *                                                                                 *
 *  Description   :  This file contains print messages for decoded bit fields      *
 *                   of structs.                                                   *
 */

/* THIS FILE IS GENERATED USING AN AUTOMATED SCRIPT... PLEASE DO NOT EDIT THIS FILE DIRECTLY !!! */


#include "osprey7_v2l8p1_decode_print.h"
#include "osprey7_v2l8p1_functions.h"

/*! @file
 */

/************************************/
/* Bitfield print/decode functions  */
/************************************/

err_code_t osprey7_v2l8p1_decode_uc_sts_ext(srds_access_t *sa__, uint16_t bits, char *buf, size_t buf_size, const char * const prepended_text) {
    size_t count = 0;
    int32_t chars_written = 0;
    UNUSED(sa__);
    if(!buf || !prepended_text) {
        return ERR_CODE_BAD_PTR_OR_INVALID_INPUT;
    }
    if(bits & (0x01 << 0)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts_ext BIT 0: dac4ck_cal_fail = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x01 << 1)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts_ext BIT 1: lt_frame_lock_toggle = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x01 << 2)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts_ext BIT 2: otp_speed_check_fail = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x0f << 3)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts_ext BITS 3-6: clk_hoffset_check = 0x%02x\n", prepended_text, (bits & (0x0f << 3)) >> 3);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x03 << 8)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts_ext BITS 8-9: pam4_eye_quality_check = 0x%02x\n", prepended_text, (bits & (0x03 << 8)) >> 8);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x01 << 10)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts_ext BIT 10: vcal_finish_at_minmax = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x01 << 11)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts_ext BIT 11: vcal_finish_above_threshold = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    return (ERR_CODE_NONE);
}
err_code_t osprey7_v2l8p1_decode_uc_sts(srds_access_t *sa__, uint8_t bits, char *buf, size_t buf_size, const char * const prepended_text) {
    size_t count = 0;
    int32_t chars_written = 0;
    UNUSED(sa__);
    if(!buf || !prepended_text) {
        return ERR_CODE_BAD_PTR_OR_INVALID_INPUT;
    }
    if(bits & (0x01 << 0)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts BIT 0: extended_sts = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x01 << 1)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts BIT 1: dc_offset_limit_fail = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x01 << 2)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts BIT 2: ate_test_done = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x01 << 4)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts BIT 4: fixed_dfe_limit_fail = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x01 << 5)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts BIT 5: rxffe_limit_fail = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x01 << 6)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts BIT 6: heye_margin_limit_fail = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    if(bits & (0x01 << 7)) {
        chars_written = USR_SNPRINTF(buf + count, buf_size - count, "%suc_sts BIT 7: veye_margin_limit_fail = 0x1\n", prepended_text);
        count += (size_t)chars_written;
        if((chars_written < 0) || (count > buf_size)) {
            return ERR_CODE_REACHED_BUF_SIZE_LIMIT;
        }
    }
    return (ERR_CODE_NONE);
}
