/*************************************************************************************
 *                                                                                   *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

/*************************************************************************************
 *************************************************************************************
 *                                                                                   *
 *  Revision      :  Id                                                              *
 *                                                                                   *
 *  Description   :  const array definitions used by the reg_dump function           *
 */


/* THIS FILE IS GENERATED USING AN AUTOMATED SCRIPT... PLEASE DO NOT EDIT THIS FILE DIRECTLY !!! */

#include "osprey7_v2l8p1_reg_dump.h"

/*! @file
 */

const uint16_t osprey7_v2l8p1_reg_dump_arr[OSPREY7_V2L8P1_REG_DUMP_SECTIONS][2] = {
    {0x0090, 0x00a0},
    {0xd080, 0xd0f0},
    {0xd100, 0xd110},
    {0xd120, 0xd140},
    {0xd150, 0xd180},
    {0xd190, 0xd240},
    {0xd300, 0xd320},
    {0xd330, 0xd360},
    {0xd400, 0xd410},
    {0xd430, 0xd440},
    {0xd470, 0xd480},
    {0xd4d0, 0xd4e0},
    {0xd500, 0xd670},
    {0xffd0, 0xffe0},
    {0xd110, 0xd120},
    {0xd140, 0xd150},
    {0xd180, 0xd190},
    {0xd320, 0xd330},
    {0xd240, 0xd250}
};
