/*
 *         
 * 
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *         
 *     
 * DO NOT EDIT THIS FILE!
 */

#ifndef _TSCO_DPLL_DIAGNOSTICS_H__H_
#define _TSCO_DPLL_DIAGNOSTICS_H__H_

#include <phymod/phymod_definitions.h>
/*set\get PRBS configuration*/
int tsco_dpll_phy_prbs_config_set(const phymod_phy_access_t* phy, uint32_t flags , const phymod_prbs_t* prbs);
int tsco_dpll_phy_prbs_config_get(const phymod_phy_access_t* phy, uint32_t flags , phymod_prbs_t* prbs);

/*Set\get PRBS enable state*/
int tsco_dpll_phy_prbs_enable_set(const phymod_phy_access_t* phy, uint32_t flags , uint32_t enable);
int tsco_dpll_phy_prbs_enable_get(const phymod_phy_access_t* phy, uint32_t flags , uint32_t* enable);

/*Get PRBS Status*/
int tsco_dpll_phy_prbs_status_get(const phymod_phy_access_t* phy, uint32_t flags, phymod_prbs_status_t* prbs_status);

/*Set\get pattern state*/
int tsco_dpll_phy_pattern_config_set(const phymod_phy_access_t* phy, const phymod_pattern_t* pattern);
int tsco_dpll_phy_pattern_config_get(const phymod_phy_access_t* phy, phymod_pattern_t* pattern);

/*Set\get pattern state*/
int tsco_dpll_phy_pattern_enable_set(const phymod_phy_access_t* phy, uint32_t enable, const phymod_pattern_t* pattern);
int tsco_dpll_phy_pattern_enable_get(const phymod_phy_access_t* phy, uint32_t* enable);

/*Get phy diagnostics information*/
int tsco_dpll_phy_pmd_info_dump(const phymod_phy_access_t* phy, const char* type);

/*Display eyescan information*/
int tsco_dpll_phy_eyescan_run(const phymod_phy_access_t* phy, uint32_t flags, phymod_eyescan_mode_t mode, const phymod_phy_eyescan_options_t* eyescan_options);

/*Get CL91 FEC Corrected Codeword Counter*/
int tsco_dpll_phy_fec_cl91_correctable_counter_get(const phymod_phy_access_t* phy, uint32_t* count);

/*Get CL91 FEC Uncorrected Codeword Counter*/
int tsco_dpll_phy_fec_cl91_uncorrectable_counter_get(const phymod_phy_access_t* phy, uint32_t* count);

/*PAM4 tx pattern set/get*/
int tsco_dpll_phy_PAM4_tx_pattern_enable_set(const phymod_phy_access_t* phy, phymod_PAM4_tx_pattern_t pattern_type, uint32_t enable);
int tsco_dpll_phy_PAM4_tx_pattern_enable_get(const phymod_phy_access_t* phy, phymod_PAM4_tx_pattern_t pattern_type, uint32_t* enable);

/* BER Projection*/
int tsco_dpll_phy_ber_proj(const phymod_phy_access_t* phy, phymod_ber_proj_mode_t mode, const phymod_phy_ber_proj_options_t* options);

/* fast BER Projection*/
int tsco_dpll_phy_fast_ber_proj_get(const phymod_phy_access_t* phy, uint32_t* ber_proj_data);

/* Get RS FEC symbol error count.*/
int tsco_dpll_phy_rsfec_symbol_error_counter_get(const phymod_phy_access_t* phy, int max_count, int* actual_count, uint32_t* error_count);

/* Link Channel Analysis Tool.*/
int tsco_dpll_phy_linkcat(const phymod_phy_access_t* phy, phymod_linkCAT_op_mode_t mode);

/* set/get pmd debug level */
int tsco_dpll_phy_pmd_lane_diag_debug_level_set(const phymod_phy_access_t* phy, uint32_t level);
int tsco_dpll_phy_pmd_lane_diag_debug_level_get(const phymod_phy_access_t* phy, uint32_t* level);

#endif /*_TSCO_DPLL_DIAGNOSTICS_H_*/
