/*
 *         
 * 
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *         
 *     
 * DO NOT EDIT THIS FILE!
 */

#ifndef _TSCO_DIAGNOSTICS_H__H_
#define _TSCO_DIAGNOSTICS_H__H_

#include <phymod/phymod_definitions.h>
/*Get CL91 FEC Corrected Codeword Counter*/
int tsco_phy_fec_cl91_correctable_counter_get(const phymod_phy_access_t* phy, uint32_t* count);

/*Get CL91 FEC Uncorrected Codeword Counter*/
int tsco_phy_fec_cl91_uncorrectable_counter_get(const phymod_phy_access_t* phy, uint32_t* count);

/* Get RS FEC symbol error count.*/
int tsco_phy_rsfec_symbol_error_counter_get(const phymod_phy_access_t* phy, int max_count, int* actual_count, uint32_t* error_count);

#endif /*_TSCO_DIAGNOSTICS_H_*/
